### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by dmkenza** [friedkeenan/monarch-wings#1]
port please on 1.19.2

**Comment by friedkeenan** [comment]
Sorry, I don't have much interest in supporting my mods for outdated versions. As far as I *know*, one thing that blocks the mod from working on 1.19.2 would be my use of `FabricPacket` which is not contained within the Fabric API for 1.19.2, but there may be other things too. But as said before, I don't really have much interest in supporting old versions, sorry.
