### ISSUE TITLE
Hi! I was wondering how difficult it would be to potentially port this mod to 1.20.1? 

### ISSUE THREAD

**Issue by cobaltkat** [friedkeenan/monarch-wings#5]
If it would take up a lot of time or effort then don't worry about it, however your mod fits perfectly into my needs. 
Thank you!

**Comment by cobaltkat** [comment]
OOPS i missed your other issue I just saw that just now... feel free to close this issue, thank you!

**Comment by friedkeenan** [comment]
Yeah, it *might* work if you just change [this line](https://github.com/friedkeenan/monarch-wings/blob/827e3ba89ee4cf8db21184f48382dcf962f3c2b1/src/main/resources/fabric.mod.json#L39) and then build the mod with `./gradlew build` but I'm not sure. Specifying proper version ranges is my kryptonite. But yeah, I'll be closing this issue. Thank you for your interest though, I seriously do appreciate it
